apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "kubernetesdemo"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "kubernetesdemo"
    spec:
      containers:
        - name: "kubernetesdemo"
          image: "kubernetescontainerregistrydemo.azurecr.io/kubernetesdemo"
          ports:
          - containerPort: 80
resources:
  requests:
     cpu: 250m
  limits:
     cpu: 500m