apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kubernetesdemo-hpa
spec:
  maxReplicas: 4 # define max replica count
  minReplicas: 1  # define min replica count
  metrics:
  - type: External
    external:
      metricName: appgw-request-count-metric
      targetAverageValue: 200
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kubernetesdemo
  targetCPUUtilizationPercentage: 20 # target CPU utilization